title: Sanghee Moon
logo: /assets/img/sanghee.png
description: A graduate researcher at the University of Kansas Medical Center [smoon(at)kumc(dot)edu]
show_downloads: false
google_analytics: UA-140852514-1
theme: jekyll-theme-minimal
author :
  name : Sanghee Moon
  email : sanghee1021@gmail.com
  github : sanghee1021
  twitter : sangheemoon
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:sanghee1021@gmail.com
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sangheemoon"
#     - label: "Facebook"
#       icon: "fab fa-fw fa-facebook-square"
#       # url: "https://facebook.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       # url: "https://github.com/"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       # url: "https://instagram.com/"
