title: Sanghee Moon
logo: /assets/img/sanghee.png
description: A graduate researcher at the University of Kansas Medical Center [smoon(at)kumc(dot)edu]
show_downloads: false
google_analytics: UA-140852514-1
theme: jekyll-theme-minimal
plugins:
  - jemoji
