title: Sanghee Moon
logo: /assets/img/sanghee.png
description: Works at Ithaca College [smoon2(at)ithaca(dot)edu]
show_downloads: false
google_analytics: UA-140852514-1
theme: jekyll-theme-minimal
plugins:
  - jemoji
  - jekyll-seo-tag
